### ISSUE TITLE
Packages suggestions

### ISSUE THREAD

**Issue by miraage** [arago/hiro-ui#22]
- `hiro-sdk`
Rename to `@hiro-ui/bootstrap`. `hiro-sdk` is not actually an sdk. If we take a closer look, it bootstraps an application rather than providing a development kit.

- `@hiro-ui/bootstrap`
Rename to `@hiro-ui/kit`. We can store simple (buttons, inputs, dropdowns, toggles, typeaheads, modals) [UI components ](https://xd.adobe.com/spec/99e18daa-f2ba-4dad-6b5a-f008096e30ec-efd0/screen/02267ec3-8da8-43d3-a8a9-ee52afd266fc/02-HIRO-KAT-Elements/)there.
I very strongly suggest not to use any library directly, but always have an adapter with the API we need.

- `@hiro-graph/implicit-oauth`
Rename to `@hiro-graph/auth`. Package would have 3 strategies: Graph, UI, Desktop. UI strategy would also have an additional option to run either iframe/redirect/popup.

**Comment by miraage** [comment]
cc @bpneal @Drache93

**Comment by bpneal** [comment]
- `@hiro-graph/implicit-oauth` => `@hiro-graph/auth` ✅ (as long as we deprecate the old one clearly)
- 3 strategies... do we need the `graph` strategy? or would this be just for testing?
- Do we still need / want the popup option?
- `@hiro-ui/bootstrap` => `@hiro-ui/kit` 🚫 I think this should stay as bootstrap
- and yes we should remove libraries like redux (was on our list anyway, just added a ticket)
- `hiro-sdk` => `@hiro-ui/bootstrap` 🚫 but lets change it to something else thats not sdk, maybe ui-wrapper ?

**Comment by miraage** [comment]
> 3 strategies... do we need the graph strategy? or would this be just for testing?
Would be useful for dev environment so you "bypass" authentication layer due to how graph auth works.

> Do we still need / want the popup option?
IMO popup/iframe is better than redirect because you lose no state

>  I think this should stay as bootstrap
My intention was to finally create a UI Kit package with basic elements
